version: 0.0
os: linux
files:
  - source: /.env.example
    destination: /home/ec2-user/node-website
  - source: /app.js
    destination: /home/ec2-user/node-website
  - source: /package.json
    destination: /home/ec2-user/node-website
  - source: /public/
    destination: /home/ec2-user/node-website/public
  - source: /views/
    destination: /home/ec2-user/node-website/views
  - source: /controllers/
    destination: /home/ec2-user/node-website/controllers
  - source: /models/
    destination: /home/ec2-user/node-website/models
  - source: /scripts/
    destination: /home/ec2-user/node-website/scripts
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
